services:
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: always
    network_mode: host
    
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:////var/lib/marzban/db.sqlite3
      - SUDO_USERNAME=admin
      - SUDO_PASSWORD=admin
      
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      
      - XRAY_EXECUTABLE_PATH=/usr/local/bin/xray
      - XRAY_ASSETS_PATH=/usr/local/share/xray
      
    volumes:
      - ~/persistent/marzban:/var/lib/marzban